// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolAttendanceManager.Models;

#nullable disable

namespace SchoolAttendanceManager.Migrations
{
    [DbContext(typeof(SchoolAttendanceDbContext))]
    partial class SchoolAttendanceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolAttendanceManager.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ImageUpload")
                        .HasMaxLength(1000)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateOnly?>("RegistrationDate")
                        .HasColumnType("date")
                        .HasColumnName("Registration_Date");

                    b.Property<string>("Role")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registra__3213E83FB061C1A0");

                    b.HasIndex("RoleId");

                    b.ToTable("Registration", (string)null);
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Result", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExamResult")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("examResult");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.HasKey("Id")
                        .HasName("PK__result__3213E83F3E1A0799");

                    b.ToTable("result", (string)null);
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3213E83F458D83D6");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.StudentDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Class")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("class");

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("Marks")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Percentage")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("percentage");

                    b.Property<int>("ResultId")
                        .HasColumnType("int")
                        .HasColumnName("resultId");

                    b.Property<string>("Section")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("SubjectsId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__studentD__3213E83F2F8603C3");

                    b.HasIndex("ResultId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectsId");

                    b.ToTable("studentDetails", (string)null);
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("Isdeleted")
                        .HasColumnType("bit")
                        .HasColumnName("isdeleted");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Subject__3213E83F8BF5D33F");

                    b.ToTable("Subject", (string)null);
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Registration", b =>
                {
                    b.HasOne("SchoolAttendanceManager.Models.Role", "RoleNavigation")
                        .WithMany("Registrations")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__Registrat__RoleI__4CA06362");

                    b.Navigation("RoleNavigation");
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.StudentDetail", b =>
                {
                    b.HasOne("SchoolAttendanceManager.Models.Result", "Result")
                        .WithMany("StudentDetails")
                        .HasForeignKey("ResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__studentDe__resul__6A30C649");

                    b.HasOne("SchoolAttendanceManager.Models.Registration", "Registration")
                        .WithMany("StudentDetails")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__studentDe__Stude__68487DD7");

                    b.HasOne("SchoolAttendanceManager.Models.Subject", "Subjects")
                        .WithMany("StudentDetails")
                        .HasForeignKey("SubjectsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK__studentDe__Subje__693CA210");

                    b.Navigation("Registration");

                    b.Navigation("Result");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Registration", b =>
                {
                    b.Navigation("StudentDetails");
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Result", b =>
                {
                    b.Navigation("StudentDetails");
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Role", b =>
                {
                    b.Navigation("Registrations");
                });

            modelBuilder.Entity("SchoolAttendanceManager.Models.Subject", b =>
                {
                    b.Navigation("StudentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
