name: SchoolResultMangement CI Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish Project
      run: dotnet publish -c Release -o ./publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: app
        path: ./publish
